//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSP.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Gamemode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Gamemode() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SSP.Localization.Gamemode", typeof(Gamemode).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changeling.
        /// </summary>
        internal static string ChangelingRoleName {
            get {
                return ResourceManager.GetString("ChangelingRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelings.
        /// </summary>
        internal static string ChangelingsGamemodeName {
            get {
                return ResourceManager.GetString("ChangelingsGamemodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended.
        /// </summary>
        internal static string ExtendedGamemodeName {
            get {
                return ResourceManager.GetString("ExtendedGamemodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixed.
        /// </summary>
        internal static string MixedGamemodeName {
            get {
                return ResourceManager.GetString("MixedGamemodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traitor.
        /// </summary>
        internal static string TraitorRoleName {
            get {
                return ResourceManager.GetString("TraitorRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traitors.
        /// </summary>
        internal static string TraitorsGamemodeName {
            get {
                return ResourceManager.GetString("TraitorsGamemodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard.
        /// </summary>
        internal static string WizardRoleName {
            get {
                return ResourceManager.GetString("WizardRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizards.
        /// </summary>
        internal static string WizardsGamemodeName {
            get {
                return ResourceManager.GetString("WizardsGamemodeName", resourceCulture);
            }
        }
    }
}
